[package]
name = "iota"
version = "0.1.1"
authors = ["viperscape <chrisfgill@gmail.com>"]
license = "MIT"
description = "authenticated communication, with an eye towards iot"

[[bin]]
name = "iota"
path = "src/bin/main.rs"


[dependencies]
rust-crypto = "*"
clock_ticks = "*"
rand = "*"