[package]
name = "iota"
version = "0.1.0"
authors = ["viperscape <chrisfgill@gmail.com>"]
license = "MIT"
description = "authenticated communication"

[[bin]]
name = "iota"
path = "src/bin/main.rs"


[dependencies]
rust-crypto = "*"
clock_ticks = "*"
rand = "*"